# Generated by Django 4.2.5 on 2023-10-03 14:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0006_alter_userbookrelation_rate"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="readers",
        ),
    ]
