# Generated by Django 4.2.5 on 2023-10-03 14:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("store", "0007_remove_book_readers"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="readers",
            field=models.ManyToManyField(
                related_name="books",
                through="store.UserBookRelation",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
